source 'https://github.com/LeiZong/ZZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ZZSpecialKit_Category_Example' do
  pod 'ZZSpecialKit_Category', :path => '../'

  target 'ZZSpecialKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
